# fly.toml app configuration file generated for thepreferredsavingsguide on 2023-12-01T12:30:13-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "thepreferredsavingsguide"
primary_region = "ord"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  PORT=8080